### ISSUE TITLE
Smoothie Escaping Function `->`

### ISSUE THREAD

**Issue by brandonparsons** [jfrolich/smoothie#10] opened 2017-01-25 22:24 UTC
Hi there,

Not sure if I'm doing something incorrectly, but trying to repeat some HTML blocks in a template that is to be processed by smoothie:

```
                        <%= Enum.map child.activities, fn(activity) -> %>
                          <tr>
                            <td><%= activity.details %></td>
                            <td><%= activity.display_time %></td>
                          </tr>
                        <% end %>
```

It would appear that smoothie is escaping the `->` at the end of the function literal:

```
                        <%= Enum.map child.activities, fn(activity) -&gt; %>
                          <tr>
                            <td style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"><%= activity.details %></td>
                            <td style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"><%= activity.display_time %></td>
                          </tr>
                        <% end %>
```

Note it has compiled to a `-&gt;`.

Is there a way I'm supposed to be doing this differently?

**Comment by jfrolich** [comment] 2017-01-26 15:23
No this is probably a bug, nice find.

**Comment by jfrolich** [comment] 2017-01-29 09:28
I have pretty simple templates. If you can find the bug I happily merge. I think it is caused by one of the escaping steps.

**Comment by jfrolich** [comment] 2017-01-29 09:31
I only have time to look into it myself in a few days. 😬

**Comment by stephenmoloney** [comment] 2017-01-29 10:31
I also have a list of things to do as long as my arm....
I think, however, something I did before *might* fix this... 
I'll try to take a look if a i get a change later

**Comment by jfrolich** [comment] 2017-01-29 14:02
I wrote a test for it and it seems to succeed, can you check our elixir-smoothie npm package version?

**Comment by jfrolich** [comment] 2017-01-29 14:50
My mistake, it was indeed not working. Published a fix as elixir-smoothie 2.0.5.

**Comment by brandonparsons** [comment] 2017-01-30 18:17
Thanks for taking a look. Sorry for the slow reply - we have a new baby in the house :)

I'm having trouble getting up and running with smoothie, so am not having much luck figuring out if this fix worked! 

Can variables in `template_params` only be primitives? Or can I pass in lists of structs?

**Comment by brandonparsons** [comment] 2017-02-01 12:28
I suspect my issues might be fixed by your new version mentioned in https://github.com/jfrolich/smoothie/issues/11

**Comment by stephenmoloney** [comment] 2017-03-31 20:26
We should just create a test for this. I'll try to get to it eventually.

**Comment by jfrolich** [comment] 2017-05-23 09:37
Yes this should be fixed

**Closed by jfrolich** 2017-05-23 09:37 UTC
Labels: question
